[project]
name = "relipmoc"
version = "0.1.0"
description = "Design space exploration tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-exclude = ["src/**/test"]

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "test" },
]
lint = [
    "ruff==0.12.12",
]
test = [
    "pytest==8.4.2",
    "pytest-cov==7.0.0",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.coverage.run]
branch = true
omit = [
    "src/**/__init__.py",
    "src/**/test/**"
]

[tool.coverage.html]
directory = "htmlcov"
